name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev lcov doxygen graphviz

    - name: Configure build
      run: |
        chmod +x configure
        ./configure --enable-tests --enable-docs --enable-sanitizers --enable-coverage

    - name: Build project
      run: make

    - name: Run tests
      run: make test

    - name: Generate documentation
      run: |
        make docs

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: build/tests/test_results.xml

    - name: Upload documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: build/docs/html

    - name: Run tests with coverage
      run: |
        cd build/tests
        ./run_tests
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/tests/coverage.info

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: build/tests/coverage.info
        fail_ci_if_error: true
