name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev lcov

    - name: Configure build
      run: |
        chmod +x configure
        ./configure --enable-tests --enable-coverage

    - name: Build project
      run: make

    - name: Run tests
      run: |
        chmod +x build/tests/run_tests.sh
        make test
        ./build/tests/run_tests.sh

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: build/tests/test_results.xml

    - name: Run tests with coverage
      run: |
        # Initialize coverage
        lcov --rc lcov_branch_coverage=1 --zerocounters --directory . --quiet
        lcov --rc lcov_branch_coverage=1 --capture --initial --directory . --output-file base.info --ignore-errors empty,mismatch,range --quiet
        
        # Run tests
        export LLVM_PROFILE_FILE="coverage-%p.profraw"
        chmod +x build/tests/run_tests.sh
        cd build/tests && ./run_tests.sh
        cd ../..
        
        # Collect coverage
        lcov --rc lcov_branch_coverage=1 --directory . --capture --output-file test.info --ignore-errors empty,mismatch,range,unused --quiet
        lcov --rc lcov_branch_coverage=1 --add-tracefile base.info --add-tracefile test.info --output-file coverage.info
        lcov --rc lcov_branch_coverage=1 --remove coverage.info '/usr/*' '*/tests/*' --output-file filtered.info
        lcov --rc lcov_branch_coverage=1 --list filtered.info --ignore-errors empty,mismatch,unused

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: filtered.info

    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: filtered.info
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: JohnnyTeutonic/chunking_cpp
        verbose: true 